"use client";

import { useState, useCallback, useRef, useEffect, useMemo } from "react";
import { useSession } from "next-auth/react";
import { useT, useLocale, type Locale } from "@/lib/i18n/context";
import HeaderAuth from "@/components/auth/HeaderAuth";
import VideoDetection from "@/components/VideoDetection";
import SocialShare from "@/components/SocialShare";
import { generateShareCard, makeShareThumb, type ShareCardLabels } from "@/lib/shareCard";
import { getBuildInfo } from "@/lib/version";

interface Evidence {
  source: string;
  type: "real" | "ai" | "neutral";
  label: string;
  detail: string;
}

interface SignalItem {
  category: "vit" | "exif" | "format" | "calibration";
  label: string;
  detail: string;
  lean: "real" | "ai" | "neutral";
  score?: number;
}

interface DetectionResult {
  aiProbability: number;
  verdict: "likely_ai" | "likely_real" | "uncertain";
  confidence: number;
  evidence: Evidence[];
  signals?: SignalItem[];
  screenRephoto?: boolean;
  processingTimeMs: number;
  fileName: string;
  fileSize: number;
}

// --- Challenge data ---
interface ChallengePair {
  id: string;
  category: string;       // emoji
  questionZh: string;
  questionEn: string;
  hintZh: string;
  hintEn: string;
  leftImage: string;       // path to image A
  rightImage: string;      // path to image B
  aiSide: "left" | "right"; // which side is AI-generated
}

const CHALLENGE_POOL: ChallengePair[] = [
  {
    id: "mountain",
    category: "🏔️",
    questionZh: "这两张山景照片，哪一张是 AI 生成的？",
    questionEn: "Which of these two mountain photos was generated by AI?",
    hintZh: "AI 常见痕迹：倒影过于完美、边缘过度平滑、天空纹理重复。",
    hintEn: "Common AI tells: overly perfect reflections, unnaturally smooth edges, repetitive sky textures.",
    leftImage: "/challenge/ai-mountain.jpg",
    rightImage: "/challenge/real-mountain.jpg",
    aiSide: "left",
  },
  {
    id: "street",
    category: "🏙️",
    questionZh: "两张城市街景，你能找出 AI 那张吗？",
    questionEn: "Two urban street scenes — can you spot the AI one?",
    hintZh: "AI 城市场景常见问题：窗户反射不自然、消防梯透视错误、阴影方向不一致。",
    hintEn: "AI urban tells: unnatural window reflections, fire escape perspective errors, inconsistent shadow directions.",
    leftImage: "/challenge/real-street.jpg",
    rightImage: "/challenge/ai-street.jpg",
    aiSide: "right",
  },
  {
    id: "beach",
    category: "🏖️",
    questionZh: "海边风光照，哪张是 AI 画的？",
    questionEn: "Beach scenery — which photo was created by AI?",
    hintZh: "AI 海景常见痕迹：海浪纹理过于规律、草地缺乏细节层次、光线方向模糊。",
    hintEn: "AI beach tells: too-regular wave patterns, flat grass detail layers, ambiguous light direction.",
    leftImage: "/challenge/ai-beach.jpg",
    rightImage: "/challenge/real-beach.jpg",
    aiSide: "left",
  },
  {
    id: "portrait",
    category: "👤",
    questionZh: "两幅人物肖像，哪一幅是 AI 生成的？",
    questionEn: "Two portraits — which one is AI-generated?",
    hintZh: "AI 肖像常见：皮肤纹理过于均匀、眼睛高光不对称、头发与头皮交界不自然。",
    hintEn: "AI portrait tells: overly uniform skin texture, asymmetric eye highlights, unnatural hairline transition.",
    leftImage: "/challenge/real-portrait.jpg",
    rightImage: "/challenge/ai-portrait.jpg",
    aiSide: "right",
  },
  {
    id: "food",
    category: "🍽️",
    questionZh: "美食照片中，哪一张出自 AI 之手？",
    questionEn: "In these food photos, which one was made by AI?",
    hintZh: "AI 美食痕迹：食材摆放过于完美、酱汁分布太均匀、餐具反光不真实。",
    hintEn: "AI food tells: too-perfect ingredient arrangement, overly even sauce distribution, unrealistic utensil reflections.",
    leftImage: "/challenge/real-food.jpg",
    rightImage: "/challenge/ai-food.jpg",
    aiSide: "right",
  },
  {
    id: "cat",
    category: "🐱",
    questionZh: "两只可爱的猫咪，哪只是 AI 假的？",
    questionEn: "Two cute cats — which one is fake (AI)?",
    hintZh: "AI 动物常见：毛发纹理重复、眼睛瞳孔形状异常、爪子细节模糊。",
    hintEn: "AI animal tells: repetitive fur textures, abnormal pupil shapes, blurry paw details.",
    leftImage: "/challenge/real-cat.jpg",
    rightImage: "/challenge/ai-cat.jpg",
    aiSide: "right",
  },
];

function pickRandomChallenge(): ChallengePair {
  const idx = Math.floor(Math.random() * CHALLENGE_POOL.length);
  return CHALLENGE_POOL[idx];
}

interface HistoryItem {
  id: string;
  thumbnail: string;
  fileName: string;
  aiProbability: number;
  verdict: DetectionResult["verdict"];
  timestamp: number;
}

const ANON_LIMIT = 1;
const USER_LIMIT = 5;

// --- Quota helpers ---
function getTodayKey() {
  const now = new Date();
  return `truelens_count_${now.getFullYear()}-${now.getMonth() + 1}-${now.getDate()}`;
}

function getDailyCount() {
  if (typeof window === "undefined") return 0;
  return parseInt(localStorage.getItem(getTodayKey()) || "0", 10);
}

function incrementDailyCount() {
  if (typeof window === "undefined") return;
  const key = getTodayKey();
  const count = getDailyCount();
  localStorage.setItem(key, String(count + 1));
  Object.keys(localStorage).forEach((k) => {
    if (k.startsWith("truelens_count_") && k !== key) {
      localStorage.removeItem(k);
    }
  });
}

function getRemainingAnonQuota() {
  return Math.max(0, ANON_LIMIT - getDailyCount());
}

// --- History helpers ---
const HISTORY_KEY = "truelens_history";
const MAX_HISTORY = 10;

function getHistory(): HistoryItem[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]");
  } catch {
    return [];
  }
}

function addToHistory(item: HistoryItem) {
  if (typeof window === "undefined") return;
  const persist = (items: HistoryItem[]) => {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(items.slice(0, MAX_HISTORY)));
  };
  try {
    const history = getHistory();
    history.unshift(item);
    persist(history);
  } catch {
    // Quota exceeded — shrink by dropping oldest entries, then retry.
    try {
      let history = getHistory();
      history.unshift(item);
      while (history.length > 1) {
        history = history.slice(0, history.length - 1);
        try {
          persist(history);
          break;
        } catch {
          // keep shrinking
        }
      }
    } catch {
      // Last resort: clear and store only the latest item.
      try {
        localStorage.removeItem(HISTORY_KEY);
        persist([item]);
      } catch {
        // storage failed — history is non-essential, ignore
      }
    }
  }
}

function clearHistory() {
  if (typeof window === "undefined") return;
  localStorage.removeItem(HISTORY_KEY);
}

// Share-card generator lives in lib/shareCard.ts (client-only, decoupled from i18n).

// --- Client-side image compression (avoids Vercel's 4.5MB request-body limit) ---
// Large phone photos / PNG screenshots are downscaled to a max dimension and
// re-encoded as JPEG, which keeps uploads small and fast.
async function compressImage(
  file: File,
  maxDim = 1024,
  quality = 0.82
): Promise<Blob> {
  const bitmap = await createImageBitmap(file);
  let { width, height } = bitmap;
  if (width > maxDim || height > maxDim) {
    const scale = Math.min(maxDim / width, maxDim / height);
    width = Math.round(width * scale);
    height = Math.round(height * scale);
  }
  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("canvas unsupported");
  ctx.drawImage(bitmap, 0, 0, width, height);
  if (typeof bitmap.close === "function") bitmap.close();
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error("toBlob failed"))),
      "image/jpeg",
      quality
    );
  });
}

// --- Tiny thumbnail for history (keeps localStorage well under the 5MB quota) ---
async function makeThumbnail(dataUrl: string, maxDim = 96): Promise<string> {
  const img = new Image();
  img.src = dataUrl;
  await img.decode();
  const scale = Math.min(maxDim / img.width, maxDim / img.height, 1);
  const w = Math.max(1, Math.round(img.width * scale));
  const h = Math.max(1, Math.round(img.height * scale));
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  canvas.getContext("2d")!.drawImage(img, 0, 0, w, h);
  return canvas.toDataURL("image/jpeg", 0.6);
}

export default function Home() {
  const t = useT();
  const { locale, setLocale } = useLocale();
  const { data: session, status: sessionStatus } = useSession();
  const isAuthenticated = sessionStatus === "authenticated" && !!session?.user;

  const [image, setImage] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [dragOver, setDragOver] = useState(false);
  const [quota, setQuota] = useState(ANON_LIMIT); // reflects actual remaining detections
  const [showDetailed, setShowDetailed] = useState(true); // professional report entitlement
  const [authUnlimited, setAuthUnlimited] = useState(false); // admin: unlimited detections
  const [userPlan, setUserPlan] = useState<string>("free");
  const [isAdminUser, setIsAdminUser] = useState(false);
  const [history, setHistory] = useState<HistoryItem[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const [feedbackState, setFeedbackState] = useState<"none" | "good" | "bad" | "submitted">("none");
  const [exportingPdf, setExportingPdf] = useState(false);
  const [showFeedbackModal, setShowFeedbackModal] = useState(false);
  const [feedbackMsg, setFeedbackMsg] = useState("");
  const [shareLoading, setShareLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [sharePreviewUrl, setSharePreviewUrl] = useState<string | null>(null);
  const [shareToast, setShareToast] = useState<string | null>(null);
  const shareBlobRef = useRef<Blob | null>(null);
  const shareIdRef = useRef<string | null>(null);
  const [challengeSelected, setChallengeSelected] = useState<"left" | "right" | null>(null);
  const [currentChallenge, setCurrentChallenge] = useState<ChallengePair | null>(null);
  const [mode, setMode] = useState<"image" | "video">("image");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const fileRef = useRef<File | null>(null);

  // Pick a random challenge on mount (client-side only)
  useEffect(() => {
    setCurrentChallenge(pickRandomChallenge());
  }, []);

  useEffect(() => {
    // Set initial quota: logged-in users get USER_LIMIT, anonymous get localStorage-based
    if (isAuthenticated) {
      setQuota(USER_LIMIT);
    } else {
      setQuota(getRemainingAnonQuota());
    }
    setHistory(getHistory());
  }, [isAuthenticated]);

  const handleFile = useCallback(
    (file: File) => {
      if (!file.type.startsWith("image/")) {
        setError(t("errors.invalidImage"));
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        setError(t("errors.fileTooLarge"));
        return;
      }

      setError(null);
      setResult(null);
      setFileName(file.name);
      setFeedbackState("none");
      fileRef.current = file;

      const reader = new FileReader();
      reader.onload = (e) => {
        setImage(e.target?.result as string);
      };
      reader.readAsDataURL(file);
    },
    [t]
  );

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragOver(false);
      const file = e.dataTransfer.files[0];
      if (file) handleFile(file);
    },
    [handleFile]
  );

  const handleDetect = async () => {
    if (!image) return;

    // For anonymous users, check localStorage quota before sending request
    if (!isAuthenticated) {
      const remaining = getRemainingAnonQuota();
      if (remaining <= 0) {
        setError(t("errors.quotaExhausted"));
        return;
      }
    }

    setLoading(true);
    setError(null);
    setFeedbackState("none");

    try {
      // Compress the image on the client to stay under Vercel's 4.5MB request
      // limit (esp. for PNG screenshots / large phone photos). If compression
      // fails or the result is still too large, retry with more aggressive
      // settings before giving up.
      //
      // IMPORTANT: files already under 2 MB are sent AS-IS without any
      // canvas recompression.  Client-side bilinear/bicubic resampling destroys
      // high-frequency fingerprints (moiré at 2–5 px, sensor noise
      // heteroscedasticity, JPEG 8×8 block grid) that our server-side detectors
      // (screen.ts, texture.ts) rely on.  Skipping compression for small files
      // preserves those signals and gives the HF vision model a sharper input.
      let blob: Blob | null = null;
      const originalBlob: Blob = fileRef.current ?? await (await fetch(image)).blob();
      if (originalBlob.size <= 2 * 1024 * 1024) {
        // Small enough — send original, no detail loss.
        blob = originalBlob;
      } else {
        const compressionAttempts: Array<[number, number]> = [
          [1920, 0.85],
          [1440, 0.80],
          [1024, 0.75],
        ];
        for (const [maxDim, quality] of compressionAttempts) {
          try {
            const candidate: Blob = fileRef.current != null
              ? await compressImage(fileRef.current, maxDim, quality)
              : await (await fetch(image)).blob();
            blob = candidate;
            // Safety net: if still huge after compression, try next level
            if (blob.size <= 3 * 1024 * 1024) break; // 3 MB safety margin
          } catch {
            // Compression failed at this level, try next
          }
        }
      }
      if (!blob) {
        blob = originalBlob; // last-resort fallback
      }

      const formData = new FormData();
      formData.append("image", blob, fileName);

      const res = await fetch("/api/detect", {
        method: "POST",
        body: formData,
      });

      // Guard against non-JSON responses (e.g. Vercel edge 413 "Request Entity
      // Too Large", proxy errors, gateway timeouts) so we surface a friendly
      // message instead of a raw JSON.parse crash.
      const contentType = res.headers.get("content-type") || "";
      let data: any;
      if (contentType.includes("application/json")) {
        const text = await res.text();
        try {
          data = JSON.parse(text);
        } catch {
          // Server claimed JSON but body is not parseable — log and surface friendly error
          console.error("[TrueLens] Malformed JSON from /api/detect:", text.slice(0, 300));
          throw new Error(t("errors.serverError"));
        }
      } else {
        const text = await res.text();
        console.error("[TrueLens] Non-JSON response from /api/detect:", text.slice(0, 200));
        throw new Error(t("errors.serverError"));
      }

      if (!res.ok) {
        throw new Error(data.error || t("errors.detectFailed"));
      }

      setResult(data.result);

      // Update entitlement + quota from server response (authoritative source)
      setShowDetailed(data.showDetailed !== false);
      setAuthUnlimited(!!data.auth?.unlimited);
      setUserPlan(data.auth?.plan || "free");
      setIsAdminUser(!!data.auth?.isAdmin);

      if (data.auth?.authenticated) {
        if (data.auth.unlimited) {
          setQuota(9999); // sentinel; display uses authUnlimited
        } else {
          setQuota(data.auth.dailyRemaining);
        }
      } else {
        incrementDailyCount();
        setQuota(getRemainingAnonQuota());
      }

      // Store a small thumbnail (not the full base64) to avoid blowing the
      // localStorage 5MB quota.
      let thumbnail = image;
      try {
        thumbnail = await makeThumbnail(image, 96);
      } catch {
        // keep the full data URL as fallback
      }

      addToHistory({
        id: `${Date.now()}`,
        thumbnail,
        fileName: data.result.fileName,
        aiProbability: data.result.aiProbability,
        verdict: data.result.verdict,
        timestamp: Date.now(),
      });
      setHistory(getHistory());

      // Scroll to result on mobile
      const el = document.getElementById("result-section");
      if (el) {
        setTimeout(() => el.scrollIntoView({ behavior: "smooth", block: "start" }), 200);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : t("errors.genericError");
      if (msg.includes("AbortError") || msg.includes("abort")) {
        setError(t("errors.timeout"));
      } else if (msg.includes("Failed to fetch") || msg.includes("fetch failed")) {
        setError(t("errors.networkError"));
      } else {
        setError(msg);
      }
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setImage(null);
    setResult(null);
    setError(null);
    setFileName("");
    setFeedbackState("none");
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleClearHistory = () => {
    clearHistory();
    setHistory([]);
  };

  // --- Share ---
  const buildCardLabels = (): ShareCardLabels => ({
    cardTitle: t("share.cardTitle"),
    cardSubtitle: t("share.cardFooter"),
    verdictAi: t("result.verdict_ai_share"),
    verdictReal: t("result.verdict_real_share"),
    verdictUncertain: t("result.verdict_uncertain_share"),
    aiProb: t("share.cardAiProb"),
    confidence: (c, ms) => t("share.cardConfidence", { confidence: c, s: (ms / 1000).toFixed(2) }),
    cta: t("share.cardCta"),
    warning: t("share.cardWarning"),
    scan: t("share.cardScan"),
    footer: t("share.cardFooter"),
    noImage: t("share.noImage"),
  });

  const buildCard = async (): Promise<Blob | null> => {
    if (!result) return null;
    const blob = await generateShareCard({
      result,
      imageDataUrl: image,
      showCta: !showDetailed,
      labels: buildCardLabels(),
    });
    shareBlobRef.current = blob;
    setSharePreviewUrl((prev) => {
      if (prev) URL.revokeObjectURL(prev);
      return URL.createObjectURL(blob);
    });
    return blob;
  };

  // Generate a preview as soon as a result is available
  useEffect(() => {
    if (result) {
      buildCard().catch(() => {});
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [result, showDetailed, image, locale]);

  const showToast = (msg: string) => {
    setShareToast(msg);
    setTimeout(() => setShareToast((cur) => (cur === msg ? null : cur)), 3000);
  };

  const downloadCard = async (blob?: Blob) => {
    const data = blob ?? shareBlobRef.current;
    if (!data) return;
    const url = URL.createObjectURL(data);
    const a = document.createElement("a");
    a.href = url;
    a.download = "truelens-result.png";
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  const copyImageToClipboard = async (blob?: Blob) => {
    const data = blob ?? shareBlobRef.current;
    if (!data) return;
    try {
      if (
        navigator.clipboard &&
        "write" in navigator.clipboard &&
        typeof ClipboardItem !== "undefined"
      ) {
        await navigator.clipboard.write([new ClipboardItem({ "image/png": data })]);
        showToast(t("share.copyImageSuccess"));
        return;
      }
    } catch {
      // fall through to download
    }
    await downloadCard(data);
    showToast(t("share.savedImage"));
  };

  const handleShare = async () => {
    if (!result) return;
    setShareLoading(true);
    try {
      const blob = shareBlobRef.current ?? (await buildCard());
      if (!blob) return;
      const file = new File([blob], "truelens-result.png", { type: "image/png" });
      const verdictText =
        result.verdict === "likely_ai"
          ? t("result.verdict_ai")
          : result.verdict === "likely_real"
            ? t("result.verdict_real")
            : t("result.verdict_uncertain");
      if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
        const shareUrl = (await createShareLink()) ?? "https://truelens.top";
        await navigator.share({
          title: t("share.title"),
          text: t("share.textTemplate", {
            aiProbability: result.aiProbability,
            verdict: verdictText,
          }),
          url: shareUrl,
          files: [file],
        });
      } else {
        // Desktop fallback: copy image to clipboard + download
        await copyImageToClipboard(blob);
        await downloadCard(blob);
        showToast(t("share.wechatHint"));
      }
    } catch {
      // Share cancelled or failed — no need to alert
    } finally {
      setShareLoading(false);
    }
  };

  const createShareLink = async (): Promise<string | null> => {
    if (!result) return null;
    if (shareIdRef.current) return `https://truelens.top/s/${shareIdRef.current}`;
    try {
      const thumb = image ? await makeShareThumb(image, 320) : null;
      const res = await fetch("/api/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ result, thumbnail: thumb, locale }),
      });
      if (!res.ok) return null;
      const data = await res.json();
      if (data?.id) {
        shareIdRef.current = data.id;
        return `https://truelens.top/s/${data.id}`;
      }
    } catch {
      // ignore
    }
    return null;
  };

  const handleCopyText = async () => {
    if (!result) return;
    const verdictText =
      result.verdict === "likely_ai"
        ? t("result.verdict_ai")
        : result.verdict === "likely_real"
          ? t("result.verdict_real")
          : t("result.verdict_uncertain");
    const link = await createShareLink();
    const text = link
      ? t("share.copyTemplateLink", {
          aiProbability: result.aiProbability,
          verdict: verdictText,
          link,
        })
      : t("share.copyTemplate", {
          aiProbability: result.aiProbability,
          verdict: verdictText,
        });
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const verdictLabel = (v: "likely_ai" | "likely_real" | "uncertain") =>
    v === "likely_ai"
      ? t("result.verdict_ai")
      : v === "likely_real"
        ? t("result.verdict_real")
        : t("result.verdict_uncertain");

  // --- Export PDF report (Pro / Business / Admin only) ---
  const handleExportPdf = async () => {
    if (!result) return;
    setExportingPdf(true);
    try {
      const { exportResultPdf } = await import("../lib/exportPdf");
      await exportResultPdf({
        aiProbability: result.aiProbability,
        verdict: result.verdict,
        confidence: result.confidence,
        evidence: result.evidence,
        signals: result.signals,
        screenRephoto: result.screenRephoto,
        processingTimeMs: result.processingTimeMs,
        fileName: result.fileName,
        fileSize: result.fileSize,
        imageDataUrl: image,
        locale,
        t,
      });
    } catch (err) {
      console.error("[TrueLens] PDF export failed:", err);
    } finally {
      setExportingPdf(false);
    }
  };

  // --- Feedback ---
  const submitEmojiFeedback = async (rating: "good" | "bad") => {
    setFeedbackState(rating);
    try {
      fetch("/api/feedback", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "emoji",
          rating,
          resultContext: result
            ? {
                aiProbability: result.aiProbability,
                verdict: result.verdict,
                fileName: result.fileName,
                processingTimeMs: result.processingTimeMs,
              }
            : null,
        }),
      });
    } catch {
      // Silent fail for feedback
    }
  };

  const submitDetailedFeedback = async () => {
    if (!feedbackMsg.trim()) return;
    try {
      await fetch("/api/feedback", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "detailed",
          message: feedbackMsg,
          rating: feedbackState === "bad" ? "bad" : undefined,
          resultContext: result
            ? {
                aiProbability: result.aiProbability,
                verdict: result.verdict,
                fileName: result.fileName,
                processingTimeMs: result.processingTimeMs,
              }
            : null,
        }),
      });
    } catch {
      // Silent
    }
    setFeedbackState("submitted");
    setShowFeedbackModal(false);
    setFeedbackMsg("");
  };

  const verdictConfig = useMemo(
    () => ({
      likely_ai: {
        label: t("result.verdict_ai"),
        color: "text-red-600",
        bgColor: "bg-red-50",
        borderColor: "border-red-200",
        icon: "⚠️",
      },
      likely_real: {
        label: t("result.verdict_real"),
        color: "text-green-600",
        bgColor: "bg-green-50",
        borderColor: "border-green-200",
        icon: "✓",
      },
      uncertain: {
        label: t("result.verdict_uncertain"),
        color: "text-yellow-600",
        bgColor: "bg-yellow-50",
        borderColor: "border-yellow-200",
        icon: "?",
      },
    }),
    [t]
  );

  const evidenceColor = {
    real: "bg-green-100 text-green-700 border-green-200",
    ai: "bg-red-100 text-red-700 border-red-200",
    neutral: "bg-gray-100 text-gray-600 border-gray-200",
  };

  const formatTime = (ts: number) => {
    const d = new Date(ts);
    const now = new Date();
    const diff = now.getTime() - d.getTime();
    if (diff < 60000) return t("history.justNow");
    if (diff < 3600000) return t("history.minutesAgo", { n: Math.floor(diff / 60000) });
    if (diff < 86400000) return t("history.hoursAgo", { n: Math.floor(diff / 3600000) });
    return d.toLocaleDateString(locale === "zh" ? "zh-CN" : "en-US");
  };

  const toggleLocale = () => {
    setLocale(locale === "zh" ? "en" : "zh");
  };

  const scrollToUpload = () => {
    const el = document.getElementById("upload-section");
    if (el) {
      el.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-slate-100">
      {/* Header */}
      <header className="border-b border-slate-200 bg-white/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-indigo-700 flex items-center justify-center text-white font-bold text-lg shrink-0">
              T
            </div>
            <div className="hidden sm:block">
              <h1 className="text-xl font-bold text-slate-900">{t("common.brand")}</h1>
              <p className="text-xs text-slate-500">{t("common.tagline")}</p>
            </div>
          </div>
          <div className="flex items-center gap-2 sm:gap-3">
            {/* Language Switcher */}
            <button
              onClick={toggleLocale}
              className="text-sm font-medium min-h-[44px] px-2 rounded-lg hover:bg-slate-100 transition-colors flex items-center gap-1"
              title={locale === "zh" ? "Switch to English" : "切换为中文"}
            >
              <span>{locale === "zh" ? "EN" : "中文"}</span>
            </button>

            {history.length > 0 && (
              <button
                onClick={() => setShowHistory(!showHistory)}
                className="text-sm text-slate-500 hover:text-slate-700 transition-colors min-h-[44px] px-2"
              >
                {showHistory ? t("header.hideHistory") : t("header.showHistory")}
              </button>
            )}
            <div className="text-sm bg-slate-100 rounded-lg px-3 py-1.5 flex items-center gap-2">
              {authUnlimited ? (
                <span className="text-indigo-600 font-semibold">
                  ∞ {t("header.unlimited")}
                </span>
              ) : (
                <span
                  className={quota > 0 ? "text-indigo-600 font-semibold" : "text-slate-400"}
                >
                  {isAuthenticated
                    ? t("header.quotaLoggedIn", { quota })
                    : t("header.quotaRemaining", { quota })}
                </span>
              )}
              {!isAuthenticated && (
                <button
                  onClick={() => {
                    // Trigger the HeaderAuth modal
                    const signupBtn = document.querySelector<HTMLButtonElement>('[data-auth-action="signup"]');
                    signupBtn?.click();
                  }}
                  className="text-xs text-indigo-500 hover:text-indigo-700 font-medium whitespace-nowrap"
                >
                  {t("header.loginForMore")}
                </button>
              )}
            </div>
            <HeaderAuth />
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-6 sm:py-8">
        {/* History Panel */}
        {showHistory && history.length > 0 && (
          <div className="mb-6 bg-white rounded-2xl shadow-sm border border-slate-200 p-5 animate-in fade-in slide-in-from-top-2 duration-300">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-slate-900 flex items-center gap-2">
                <span>📜</span> {t("history.title", { count: history.length })}
              </h3>
              <button
                onClick={handleClearHistory}
                className="text-xs text-slate-400 hover:text-red-500 transition-colors min-h-[44px] px-2"
              >
                {t("history.clear")}
              </button>
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3">
              {history.map((item) => (
                <div
                  key={item.id}
                  className="relative group cursor-pointer rounded-lg overflow-hidden border border-slate-200"
                  onClick={() => {
                    setImage(item.thumbnail);
                    setFileName(item.fileName);
                    setResult(null);
                    setShowHistory(false);
                    setFeedbackState("none");
                  }}
                >
                  <img
                    src={item.thumbnail}
                    alt={item.fileName}
                    className="w-full h-24 object-cover"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent flex flex-col justify-end p-2">
                    <span
                      className={`text-xs font-bold ${
                        item.verdict === "likely_ai"
                          ? "text-red-300"
                          : item.verdict === "likely_real"
                            ? "text-green-300"
                            : "text-yellow-300"
                      }`}
                    >
                      {item.aiProbability}% AI
                    </span>
                    <span className="text-xs text-white/70 truncate">
                      {formatTime(item.timestamp)}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* 图片 / 视频 切换 Tab */}
        <div className="flex items-stretch gap-2 mb-6 bg-white rounded-xl border border-slate-200 p-1 w-full sm:w-fit">
          <button
            onClick={() => setMode("image")}
            className={`flex-1 sm:flex-none min-h-[44px] px-5 rounded-lg font-medium text-sm transition-colors ${mode === "image" ? "bg-indigo-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}
          >
            🖼️ {t("video.tabImage")}
          </button>
          <button
            onClick={() => setMode("video")}
            className={`flex-1 sm:flex-none min-h-[44px] px-5 rounded-lg font-medium text-sm transition-colors ${mode === "video" ? "bg-indigo-600 text-white" : "text-slate-600 hover:bg-slate-100"}`}
          >
            🎬 {t("video.tabVideo")}
          </button>
        </div>

        {/* Challenge */}
        {!image && mode === "image" && currentChallenge && (
          <section className="mb-8 sm:mb-10">
            {challengeSelected === null ? (
              <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 sm:p-6">
                <div className="text-center mb-5">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full bg-indigo-100 text-indigo-700 text-xs font-semibold mb-3">
                    🧩 {t("challenge.title")}
                  </span>
                  <h2 className="text-xl sm:text-2xl font-bold text-slate-900 mb-2">
                    <span className="mr-1.5">{currentChallenge.category}</span>
                    {locale === "zh" ? currentChallenge.questionZh : currentChallenge.questionEn}
                  </h2>
                  <p className="text-sm sm:text-base text-slate-600 max-w-xl mx-auto">
                    {t("challenge.subtitle")}
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  {/* Photo A (left) */}
                  <button
                    onClick={() => setChallengeSelected("left")}
                    className="group relative rounded-xl overflow-hidden border-2 border-slate-200 hover:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all text-left"
                  >
                    <div className="aspect-[3/2] relative">
                      <img
                        src={currentChallenge.leftImage}
                        alt={locale === "zh" ? "照片 A" : "Photo A"}
                        className="w-full h-full object-cover"
                      />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors" />
                    </div>
                    <div className="p-3 bg-slate-50 flex items-center justify-between">
                      <span className="font-medium text-slate-700 text-sm">{locale === "zh" ? "照片 A" : "Photo A"}</span>
                      <span className="text-xs text-indigo-600 font-medium opacity-0 group-hover:opacity-100 transition-opacity">
                        {t("challenge.aiLabel")}?
                      </span>
                    </div>
                  </button>

                  {/* Photo B (right) */}
                  <button
                    onClick={() => setChallengeSelected("right")}
                    className="group relative rounded-xl overflow-hidden border-2 border-slate-200 hover:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 transition-all text-left"
                  >
                    <div className="aspect-[3/2] relative">
                      <img
                        src={currentChallenge.rightImage}
                        alt={locale === "zh" ? "照片 B" : "Photo B"}
                        className="w-full h-full object-cover"
                      />
                      <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors" />
                    </div>
                    <div className="p-3 bg-slate-50 flex items-center justify-between">
                      <span className="font-medium text-slate-700 text-sm">{locale === "zh" ? "照片 B" : "Photo B"}</span>
                      <span className="text-xs text-indigo-600 font-medium opacity-0 group-hover:opacity-100 transition-opacity">
                        {t("challenge.aiLabel")}?
                      </span>
                    </div>
                  </button>
                </div>
              </div>
            ) : (
              <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-5 sm:p-6 animate-in fade-in duration-300">
                <div className="text-center mb-5">
                  <h2 className={`text-xl sm:text-2xl font-bold mb-2 ${
                    challengeSelected === currentChallenge.aiSide ? "text-green-600" : "text-red-600"
                  }`}>
                    {challengeSelected === currentChallenge.aiSide
                      ? t("challenge.correct")
                      : t("challenge.wrong")}
                  </h2>
                  <p className="text-sm sm:text-base text-slate-600 max-w-xl mx-auto">
                    {locale === "zh" ? currentChallenge.hintZh : currentChallenge.hintEn}
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-5">
                  {/* Left photo */}
                  <div className={`relative rounded-xl overflow-hidden border-2 ${
                    currentChallenge.aiSide === "left" ? "border-red-300" : "border-green-300"
                  }`}>
                    <div className="aspect-[3/2] relative">
                      <img
                        src={currentChallenge.leftImage}
                        alt={locale === "zh" ? "照片 A" : "Photo A"}
                        className="w-full h-full object-cover"
                      />
                      <div className={`absolute top-3 left-3 px-2.5 py-1 rounded-md text-white text-xs font-bold shadow-sm ${
                        currentChallenge.aiSide === "left" ? "bg-red-600" : "bg-green-600"
                      }`}>
                        {currentChallenge.aiSide === "left" ? t("challenge.aiLabel") : t("challenge.realLabel")}
                      </div>
                    </div>
                    <div className={`p-3 text-center text-sm font-medium ${
                      currentChallenge.aiSide === "left" ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"
                    }`}>
                      {locale === "zh" ? "照片 A" : "Photo A"}
                    </div>
                  </div>

                  {/* Right photo */}
                  <div className={`relative rounded-xl overflow-hidden border-2 ${
                    currentChallenge.aiSide === "right" ? "border-red-300" : "border-green-300"
                  }`}>
                    <div className="aspect-[3/2] relative">
                      <img
                        src={currentChallenge.rightImage}
                        alt={locale === "zh" ? "照片 B" : "Photo B"}
                        className="w-full h-full object-cover"
                      />
                      <div className={`absolute top-3 left-3 px-2.5 py-1 rounded-md text-white text-xs font-bold shadow-sm ${
                        currentChallenge.aiSide === "right" ? "bg-red-600" : "bg-green-600"
                      }`}>
                        {currentChallenge.aiSide === "right" ? t("challenge.aiLabel") : t("challenge.realLabel")}
                      </div>
                    </div>
                    <div className={`p-3 text-center text-sm font-medium ${
                      currentChallenge.aiSide === "right" ? "bg-red-50 text-red-700" : "bg-green-50 text-green-700"
                    }`}>
                      {locale === "zh" ? "照片 B" : "Photo B"}
                    </div>
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                  <button
                    onClick={scrollToUpload}
                    className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-3 px-6 rounded-xl transition-colors min-h-[48px] flex items-center gap-2"
                  >
                    <span>🔍</span> {t("challenge.cta")}
                  </button>
                  <button
                    onClick={() => {
                      setChallengeSelected(null);
                      setCurrentChallenge(pickRandomChallenge());
                    }}
                    className="text-slate-500 hover:text-slate-700 font-medium py-3 px-6 rounded-xl transition-colors min-h-[48px]"
                  >
                    {t("challenge.tryAgain")}
                  </button>
                </div>
              </div>
            )}
          </section>
        )}

        {/* Hero */}
        {!image && mode === "image" && (
          <div className="text-center mb-6 sm:mb-8">
            <h2 className="text-2xl sm:text-3xl font-bold text-slate-900 mb-3">
              {t("hero.title")}
            </h2>
            <p className="text-slate-600 max-w-2xl mx-auto text-sm sm:text-base">
              {t("hero.description")}
            </p>
          </div>
        )}

        {/* Upload Area */}
        {!image && mode === "image" && (
          <div
            id="upload-section"
            onDragOver={(e) => {
              e.preventDefault();
              setDragOver(true);
            }}
            onDragLeave={() => setDragOver(false)}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
            className={`border-2 border-dashed rounded-2xl p-8 sm:p-12 text-center cursor-pointer transition-all min-h-[200px] sm:min-h-[240px] flex flex-col items-center justify-center ${
              dragOver
                ? "border-indigo-500 bg-indigo-50"
                : "border-slate-300 bg-white hover:border-indigo-400 hover:bg-slate-50"
            }`}
          >
            <div className="text-4xl sm:text-5xl mb-4">📸</div>
            <p className="text-lg font-medium text-slate-700 mb-1">{t("upload.dropHint")}</p>
            <div className="flex flex-col sm:flex-row gap-3 mt-3">
              <button
                className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-3 px-6 rounded-xl transition-colors min-h-[48px] flex items-center gap-2"
                onClick={(e) => {
                  e.stopPropagation();
                  fileInputRef.current?.click();
                }}
              >
                <span>📁</span> {t("upload.selectImage")}
              </button>
              <button
                className="bg-slate-100 hover:bg-slate-200 text-slate-700 font-medium py-3 px-6 rounded-xl transition-colors min-h-[48px] flex items-center gap-2 border border-slate-200"
                onClick={(e) => {
                  e.stopPropagation();
                  const input = document.createElement("input");
                  input.type = "file";
                  input.accept = "image/*";
                  input.capture = "environment";
                  input.onchange = (ev) => {
                    const file = (ev.target as HTMLInputElement).files?.[0];
                    if (file) handleFile(file);
                  };
                  input.click();
                }}
              >
                <span>📷</span> {t("upload.takePhoto")}
              </button>
            </div>
            <p className="text-sm text-slate-400 mt-4">{t("upload.supportedFormats")}</p>
            <p className="text-xs text-slate-400 mt-1 max-w-md">{t("upload.note")}</p>
            <p className="text-xs text-amber-500/90 mt-1 max-w-md">
              <span className="font-bold text-red-600">{t("upload.screenWarning")}</span>
              <span>。{t("upload.screenWarningDetail")}</span>
            </p>
            {!isAuthenticated && !showHistory && (
              <p className="mt-3 text-sm text-indigo-600 font-medium">
                <button
                  onClick={() => {
                    const signupBtn = document.querySelector<HTMLButtonElement>('[data-auth-action="signup"]');
                    signupBtn?.click();
                  }}
                  className="hover:underline"
                >
                  {quota > 0
                    ? t("upload.loginEncouragement")
                    : t("upload.loginEncouragementExhausted")}
                </button>
              </p>
            )}
            {!authUnlimited && quota === 0 && (
              <p className="mt-1 text-sm text-orange-500">{t("upload.quotaExhaustedHint")}</p>
            )}
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              className="hidden"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (file) handleFile(file);
              }}
            />
          </div>
        )}

        {/* Image Preview + Result */}
        {image && mode === "image" && (
          <div className="space-y-5">
            {/* Image Preview */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
              <div className="flex flex-col sm:flex-row">
                <div className="sm:w-1/2 relative">
                  <img
                    src={image}
                    alt="Image to analyze"
                    className="w-full h-56 sm:h-72 object-cover"
                  />
                </div>
                <div className="sm:w-1/2 p-5 sm:p-6 flex flex-col justify-between">
                  <div>
                    <p className="text-sm text-slate-500 mb-1">{t("upload.fileName")}</p>
                    <p className="font-medium text-slate-900 truncate">{fileName}</p>
                    <p className="text-xs text-slate-400 mt-2">
                      {authUnlimited
                        ? t("upload.quotaInfo", { quota: "∞" })
                        : quota > 0
                          ? t("upload.quotaInfo", { quota })
                          : t("upload.quotaExhaustedBtn")}
                    </p>
                  </div>
                  <div className="mt-4 flex gap-3">
                    <button
                      onClick={handleDetect}
                      disabled={loading}
                      className="flex-1 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-300 text-white font-medium py-3.5 px-6 rounded-xl transition-colors min-h-[48px]"
                    >
                      {loading ? (
                        <span className="flex items-center justify-center gap-2">
                          <svg
                            className="animate-spin h-5 w-5"
                            viewBox="0 0 24 24"
                          >
                            <circle
                              className="opacity-25"
                              cx="12"
                              cy="12"
                              r="10"
                              stroke="currentColor"
                              strokeWidth="4"
                              fill="none"
                            />
                            <path
                              className="opacity-75"
                              fill="currentColor"
                              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                            />
                          </svg>
                          {t("common.loading")}
                        </span>
                      ) : (
                        t("upload.detect")
                      )}
                    </button>
                    <button
                      onClick={handleReset}
                      className="px-5 py-3.5 border border-slate-300 text-slate-700 font-medium rounded-xl hover:bg-slate-50 transition-colors min-h-[48px] shrink-0"
                    >
                      {t("upload.changeImage")}
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Error */}
            {error && (
              <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-red-700 text-sm flex items-start gap-3">
                <span className="text-lg shrink-0">❌</span>
                <div>
                  <p>{error}</p>
                  {error.includes(t("errors.quotaExhausted")) && (
                    <p className="mt-2 text-xs text-red-500">{t("errors.proComing")}</p>
                  )}
                </div>
              </div>
            )}

            {/* Result */}
            {result && mode === "image" && (
              <div id="result-section" className="space-y-4 animate-in fade-in duration-500">
                {/* Screen re-photo advisory: shown to ALL users (regardless of
                    membership) because the unreliable verdict needs explaining
                    even for anonymous / free-tier users. Placed ABOVE the verdict
                    box so the caveat is seen before the AI% conclusion. */}
                {result.screenRephoto && (
                  <div className="bg-amber-50 border border-amber-200 rounded-2xl p-5">
                    <p className="text-sm text-amber-800 flex items-start gap-2">
                      <span className="text-base leading-none">⚠️</span>
                      <span>{t("result.screenTip")}</span>
                    </p>
                  </div>
                )}

                {/* Verdict Card — polished, more professional layout */}
                <div
                  className={`relative overflow-hidden ${verdictConfig[result.verdict].bgColor} ${
                    verdictConfig[result.verdict].borderColor
                  } border rounded-2xl p-5 sm:p-7 shadow-sm`}
                >
                  {/* Subtle background accent */}
                  <div
                    className={`absolute -top-16 -right-16 w-48 h-48 rounded-full opacity-10 ${
                      result.verdict === "likely_ai"
                        ? "bg-red-500"
                        : result.verdict === "likely_real"
                          ? "bg-green-500"
                          : "bg-yellow-500"
                    }`}
                  />

                  <div className="relative flex items-start justify-between mb-5 gap-3">
                    <div className="flex items-center gap-3 min-w-0">
                      <div
                        className={`shrink-0 w-12 h-12 rounded-2xl flex items-center justify-center text-2xl shadow-sm ${
                          result.verdict === "likely_ai"
                            ? "bg-red-100"
                            : result.verdict === "likely_real"
                              ? "bg-green-100"
                              : "bg-yellow-100"
                        }`}
                      >
                        {verdictConfig[result.verdict].icon}
                      </div>
                      <div className="min-w-0">
                        <p
                          className={`text-xl sm:text-2xl font-bold tracking-tight ${verdictConfig[result.verdict].color}`}
                        >
                          {verdictConfig[result.verdict].label}
                        </p>
                        <p className="text-sm text-slate-500 mt-0.5">
                          {t("result.confidence", { value: result.confidence })}
                        </p>
                      </div>
                    </div>
                    <div className="text-right shrink-0">
                      <p className="text-xs text-slate-500 font-medium uppercase tracking-wider">
                        {t("result.aiProbability")}
                      </p>
                      <p
                        className={`text-3xl sm:text-4xl font-bold tabular-nums tracking-tight ${
                          result.aiProbability >= 50 ? "text-red-600" : "text-green-600"
                        }`}
                      >
                        {result.aiProbability}<span className="text-lg sm:text-xl font-medium text-slate-500">%</span>
                      </p>
                    </div>
                  </div>

                  {/* Probability Bar — taller, with tick marks for 50% threshold */}
                  <div className="relative h-4 sm:h-5 bg-slate-200/70 rounded-full overflow-visible">
                    <div
                      className={`absolute left-0 top-0 h-full rounded-full transition-all duration-1000 ${
                        result.aiProbability >= 50
                          ? "bg-gradient-to-r from-orange-400 via-red-400 to-red-500"
                          : "bg-gradient-to-r from-green-400 to-green-500"
                      }`}
                      style={{ width: `${result.aiProbability}%` }}
                    />
                    {/* 50% threshold tick */}
                    <div className="absolute top-0 bottom-0 left-1/2 w-px bg-slate-400/50" />
                  </div>
                  <div className="flex justify-between mt-2 text-xs text-slate-500">
                    <span className="font-medium">{t("result.prob_real")}</span>
                    <span className="font-medium">{t("result.prob_ai")}</span>
                  </div>
                </div>

                {/* Share */}
                <div className="bg-white border border-slate-200 rounded-2xl p-5">
                  <p className="text-sm font-medium text-slate-700 mb-3">
                    {t("share.shareResult")}
                  </p>

                  {/* Live preview of the shareable result card */}
                  {sharePreviewUrl && (
                    <div className="mb-4 rounded-xl overflow-hidden border border-slate-200 bg-slate-50">
                      <img src={sharePreviewUrl} alt="share preview" className="w-full h-auto" />
                    </div>
                  )}

                  <div className="flex flex-wrap items-center gap-3">
                    <button
                      onClick={handleShare}
                      disabled={shareLoading}
                      className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-3 px-5 rounded-xl transition-colors min-h-[48px]"
                    >
                      <span>📤</span>{" "}
                      {shareLoading ? t("share.generating") : t("share.shareImage")}
                    </button>
                    <button
                      onClick={() => copyImageToClipboard()}
                      className="flex items-center gap-2 text-slate-700 font-medium py-3 px-5 rounded-xl border border-slate-200 hover:bg-slate-50 transition-colors min-h-[48px]"
                    >
                      <span>🖼️</span> {t("share.copyImage")}
                    </button>
                    <button
                      onClick={() => downloadCard()}
                      className="flex items-center gap-2 text-slate-700 font-medium py-3 px-5 rounded-xl border border-slate-200 hover:bg-slate-50 transition-colors min-h-[48px]"
                    >
                      <span>💾</span> {t("share.saveImage")}
                    </button>
                    <button
                      onClick={handleCopyText}
                      className="flex items-center gap-2 text-slate-700 font-medium py-3 px-5 rounded-xl border border-slate-200 hover:bg-slate-50 transition-colors min-h-[48px]"
                    >
                      <span>📋</span> {copied ? t("share.copied") : t("share.copyText")}
                    </button>
                  </div>

                  <SocialShare
                    linkResolver={createShareLink}
                    shareText={t("share.textTemplate", {
                      aiProbability: result.aiProbability,
                      verdict: verdictLabel(result.verdict),
                    })}
                    shareTitle={t("share.title")}
                  />

                  {shareToast && (
                    <p className="mt-2 text-xs text-indigo-600">{shareToast}</p>
                  )}
                  {copied && !shareToast && (
                    <p className="mt-2 text-xs text-green-600">{t("share.copySuccess")}</p>
                  )}
                  <p className="mt-2 text-xs text-slate-400">{t("share.wechatHint")}</p>
                </div>

                {/* Feedback */}
                <div className="bg-white border border-slate-200 rounded-2xl p-5">
                  <p className="text-sm font-medium text-slate-700 mb-3">
                    {feedbackState === "submitted" ? t("feedback.thanks") : t("feedback.title")}
                  </p>
                  {feedbackState === "submitted" ? (
                    <p className="text-sm text-slate-500">{t("feedback.thanksDesc")}</p>
                  ) : (
                    <div className="flex items-center gap-3">
                      <button
                        onClick={() => submitEmojiFeedback("good")}
                        className={`min-h-[48px] px-5 rounded-xl border-2 text-lg transition-all ${
                          feedbackState === "good"
                            ? "border-green-500 bg-green-50"
                            : "border-slate-200 hover:border-green-300 hover:bg-green-50"
                        }`}
                      >
                        👍 {t("feedback.accurate")}
                      </button>
                      <button
                        onClick={() => {
                          submitEmojiFeedback("bad");
                          setShowFeedbackModal(true);
                        }}
                        className={`min-h-[48px] px-5 rounded-xl border-2 text-lg transition-all ${
                          feedbackState === "bad"
                            ? "border-red-500 bg-red-50"
                            : "border-slate-200 hover:border-red-300 hover:bg-red-50"
                        }`}
                      >
                        👎 {t("feedback.inaccurate")}
                      </button>
                      <a
                        href="https://github.com/yklan0930/truelens/issues/new"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sm text-slate-400 hover:text-indigo-500 transition-colors ml-auto min-h-[44px] flex items-center"
                      >
                        💬 {t("feedback.reportIssue")}
                      </a>
                    </div>
                  )}
                </div>

                {/* Evidence / Professional Report (gated by membership) */}
                {showDetailed ? (
                  <div className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-6">
                    <div className="flex items-center justify-between mb-4 gap-3 flex-wrap">
                      <h3 className="font-bold text-slate-900 flex items-center gap-2">
                        <span>🔍</span> {t("result.evidenceTitle")}
                      </h3>
                      <button
                        onClick={handleExportPdf}
                        disabled={exportingPdf}
                        className="flex items-center gap-2 bg-slate-900 hover:bg-slate-800 disabled:opacity-60 text-white text-sm font-medium py-2 px-4 rounded-xl transition-colors min-h-[40px]"
                      >
                        <span>📄</span>
                        {exportingPdf ? t("share.exportingPdf") : t("share.exportPdf")}
                      </button>
                    </div>
                    <div className="space-y-3">
                      {(result.signals && result.signals.length > 0
                        ? result.signals.map((s) => ({
                            type: s.lean,
                            label: s.label,
                            detail: s.detail,
                            extra: s.score != null ? `${s.score}%` : "",
                          }))
                        : result.evidence.map((ev) => ({
                            type: ev.type,
                            label: ev.label,
                            detail: ev.detail,
                            extra: ev.source,
                          }))
                      ).map((item, i) => (
                        <div
                          key={i}
                          className={`p-3 rounded-lg border ${evidenceColor[item.type]}`}
                        >
                          <div className="flex items-center justify-between">
                            <span className="font-medium text-sm">{item.label}</span>
                            {item.extra && (
                              <span className="text-xs opacity-70">{item.extra}</span>
                            )}
                          </div>
                          <p className="text-xs mt-1 opacity-80">{item.detail}</p>
                        </div>
                      ))}
                    </div>

                    <div className="mt-4 pt-4 border-t border-slate-100 flex justify-between text-xs text-slate-400">
                      <span>
                        {t("result.fileSize", { size: (result.fileSize / 1024).toFixed(0) })}
                      </span>
                      <span>
                        {t("result.processingTime", { s: (result.processingTimeMs / 1000).toFixed(2) })}
                      </span>
                    </div>
                  </div>
                ) : (
                  <div className="bg-gradient-to-br from-slate-900 to-indigo-900 rounded-2xl p-6 text-center text-white shadow-sm">
                    <div className="text-3xl mb-2">🔒</div>
                    <h3 className="font-bold text-lg mb-1">{t("paywall.title")}</h3>
                    <p className="text-sm text-white/70 mb-4">{t("paywall.desc")}</p>
                    <button
                      onClick={() => {
                        const signupBtn = document.querySelector<HTMLButtonElement>(
                          '[data-auth-action="signup"]'
                        );
                        signupBtn?.click();
                      }}
                      className="bg-white text-indigo-700 font-semibold py-2.5 px-6 rounded-xl hover:bg-indigo-50 transition-colors min-h-[44px]"
                    >
                      {t("paywall.cta")}
                    </button>
                    <p className="text-xs text-white/50 mt-3">{t("paywall.note")}</p>
                  </div>
                )}

                {/* Disclaimer */}
                <p className="text-xs text-slate-400 text-center px-4">
                  {t("result.disclaimer")}
                </p>
              </div>
            )}
          </div>
        )}

        {/* Video detection mode */}
        {mode === "video" && (
          <VideoDetection />
        )}

        {/* Features (when no image) */}
        {!image && mode === "image" && (
          <>
          <div className="mt-12 grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-white rounded-xl p-5 border border-slate-200">
              <div className="text-2xl mb-2">🧠</div>
              <h3 className="font-bold text-slate-900 mb-1">
                {t("features.deepLearning.title")}
              </h3>
              <p className="text-sm text-slate-500">{t("features.deepLearning.desc")}</p>
            </div>
            <div className="bg-white rounded-xl p-5 border border-slate-200">
              <div className="text-2xl mb-2">📋</div>
              <h3 className="font-bold text-slate-900 mb-1">
                {t("features.exifAnalysis.title")}
              </h3>
              <p className="text-sm text-slate-500">{t("features.exifAnalysis.desc")}</p>
            </div>
            <div className="bg-white rounded-xl p-5 border border-slate-200">
              <div className="text-2xl mb-2">⚡</div>
              <h3 className="font-bold text-slate-900 mb-1">
                {t("features.fastResult.title")}
              </h3>
              <p className="text-sm text-slate-500">{t("features.fastResult.desc")}</p>
            </div>
          </div>

          {/* How It Works */}
          <div className="mt-12">
            <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">
              {t("howItWorks.title")}
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="bg-white rounded-xl p-5 border border-slate-200 text-center">
                <div className="w-10 h-10 rounded-full bg-indigo-100 text-indigo-600 font-bold text-lg flex items-center justify-center mx-auto mb-3">
                  1
                </div>
                <h3 className="font-bold text-slate-900 mb-1">{t("howItWorks.step1Title")}</h3>
                <p className="text-sm text-slate-500">{t("howItWorks.step1Desc")}</p>
              </div>
              <div className="bg-white rounded-xl p-5 border border-slate-200 text-center">
                <div className="w-10 h-10 rounded-full bg-indigo-100 text-indigo-600 font-bold text-lg flex items-center justify-center mx-auto mb-3">
                  2
                </div>
                <h3 className="font-bold text-slate-900 mb-1">{t("howItWorks.step2Title")}</h3>
                <p className="text-sm text-slate-500">{t("howItWorks.step2Desc")}</p>
              </div>
              <div className="bg-white rounded-xl p-5 border border-slate-200 text-center">
                <div className="w-10 h-10 rounded-full bg-indigo-100 text-indigo-600 font-bold text-lg flex items-center justify-center mx-auto mb-3">
                  3
                </div>
                <h3 className="font-bold text-slate-900 mb-1">{t("howItWorks.step3Title")}</h3>
                <p className="text-sm text-slate-500">{t("howItWorks.step3Desc")}</p>
              </div>
            </div>
          </div>

          {/* FAQ */}
          <div className="mt-12">
            <h2 className="text-xl font-bold text-slate-900 mb-6 text-center">
              {t("faq.title")}
            </h2>
            <div className="space-y-3 max-w-2xl mx-auto">
              {[
                { q: t("faq.q1"), a: t("faq.a1") },
                { q: t("faq.q2"), a: t("faq.a2") },
                { q: t("faq.q3"), a: t("faq.a3") },
                { q: t("faq.q4"), a: t("faq.a4") },
                { q: t("faq.q5"), a: t("faq.a5") },
                { q: t("faq.q6"), a: t("faq.a6") },
              ].map((item, i) => (
                <details key={i} className="bg-white rounded-xl border border-slate-200 group">
                  <summary className="cursor-pointer p-4 font-medium text-slate-900 flex items-center justify-between list-none">
                    {item.q}
                    <span className="text-slate-400 group-open:rotate-180 transition-transform">▾</span>
                  </summary>
                  <div className="px-4 pb-4 text-sm text-slate-600 leading-relaxed">
                    {item.a}
                  </div>
                </details>
              ))}
            </div>
          </div>
          </>
        )}
      </main>

      {/* Feedback Modal */}
      {showFeedbackModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl p-6 max-w-md w-full shadow-xl">
            <h3 className="font-bold text-lg text-slate-900 mb-3">
              {t("feedback.modalTitle")}
            </h3>
            <p className="text-sm text-slate-500 mb-4">{t("feedback.modalDesc")}</p>
            <textarea
              value={feedbackMsg}
              onChange={(e) => setFeedbackMsg(e.target.value)}
              placeholder={t("feedback.modalPlaceholder")}
              className="w-full border border-slate-200 rounded-xl p-3 text-sm min-h-[100px] resize-y focus:outline-none focus:border-indigo-400"
              autoFocus
            />
            <div className="flex gap-3 mt-4">
              <button
                onClick={() => {
                  setShowFeedbackModal(false);
                  setFeedbackMsg("");
                  setFeedbackState("none");
                }}
                className="flex-1 py-3 border border-slate-200 rounded-xl text-slate-600 font-medium min-h-[48px]"
              >
                {t("feedback.cancel")}
              </button>
              <button
                onClick={submitDetailedFeedback}
                disabled={!feedbackMsg.trim()}
                className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-700 disabled:bg-slate-300 text-white rounded-xl font-medium min-h-[48px]"
              >
                {t("feedback.submit")}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="border-t border-slate-200 mt-12">
        <div className="max-w-4xl mx-auto px-4 py-6 text-center text-sm text-slate-400 space-y-2">
          <p>{t("footer.description")}</p>
          <p
            className="inline-flex items-center justify-center gap-1.5 flex-wrap"
            title={
              getBuildInfo().sha
                ? `Build ${getBuildInfo().version} · ${getBuildInfo().sha}`
                : `Build ${getBuildInfo().version}`
            }
          >
            <span className="text-slate-500 font-medium">truelens.top</span>
            <span className="text-slate-300">·</span>
            <span className="text-slate-400 font-mono text-xs">v{getBuildInfo().version}{getBuildInfo().sha ? ` · ${getBuildInfo().sha}` : ""}</span>
            <span className="text-slate-300">·</span>
            <span>© 2026 Michael &amp; 小毕</span>
          </p>
          <div className="flex items-center justify-center gap-4 mt-1">
            <a
              href="https://github.com/yklan0930/truelens"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-indigo-500 transition-colors"
            >
              💻 {t("footer.github")}
            </a>
            <a
              href="https://github.com/yklan0930/truelens/issues/new"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-indigo-500 transition-colors"
            >
              💬 {t("footer.feedback")}
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
